version: '3'
services:
  ansible:
    image: "ansible_eda"
    stdin_open: true
    tty: true        

#  web:
#    image: "docker.io/nginx"
#   volumes:
#     - ./templates:/etc/nginx/templates
#   ports:
#     - "8080:80"
#   environment:
#     - NGINX_HOST=foobar.com
#     - NGINX_PORT=80

#  kafka:
#    image: docker.io/bitnami/kafka:3.4
#    ports:
#      - "9092:9092"
#    volumes:
#      - "kafka_data:/bitnami"
#    environment:
#      - ALLOW_PLAINTEXT_LISTENER=yes
#
#  postgresql:
#    image: docker.io/bitnami/postgresql:15
#    volumes:
#      - 'postgresql_data:/bitnami/postgresql'
#    environment:
#      - POSTGRESQL_DATABASE=bitnami_gitea
#      - POSTGRESQL_USERNAME=bn_gitea
#     - POSTGRESQL_PASSWORD=bitnami1
#     # ALLOW_EMPTY_PASSWORD is recommended only for development.
#     - ALLOW_EMPTY_PASSWORD=yes
# gitea:
#   image: docker.io/bitnami/gitea:1
#   volumes:
#     - 'gitea_data:/bitnami/gitea'
#   environment:
#     - GITEA_DATABASE_HOST=postgresql
#     - GITEA_DATABASE_NAME=bitnami_gitea
#     - GITEA_DATABASE_USERNAME=bn_gitea
#     - GITEA_DATABASE_PASSWORD=bitnami1
#   ports:
#     - '3000:3000'
#     - '2222:2222'

#volumes:
#  postgresql_data:
#   driver: local
# gitea_data:
#   driver: local
# kafka_data:
#   driver: local
